#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the project root directory (the parent of webview)
const projectRoot = path.resolve(__dirname, '../..');
const buildGradlePath = path.join(projectRoot, 'build.gradle');

// Read the build.gradle file
const buildGradleContent = fs.readFileSync(buildGradlePath, 'utf8');

// The version the release is cut under: Gradle's buildWebview task sets
// RELEASE_VERSION from the tag the Build Plugin workflow passed as
// -PreleaseVersion, so the version shown in the UI matches the git tag.
// A plain `npm run build` has no tag to go by and falls back to build.gradle.
let version;
const injectedVersion = process.env.RELEASE_VERSION;

if (injectedVersion) {
  version = injectedVersion;
  console.log(`Using RELEASE_VERSION from Gradle: ${version}`);
} else {
  // build.gradle: version = findProperty('releaseVersion') ?: '1.0.0-opencode.1'
  // The fallback literal is the last quoted string on the line — any earlier
  // ones are property names passed to findProperty().
  const versionLine = buildGradleContent.match(/^version\s*=(.*)$/m);
  const quoted = versionLine && versionLine[1].match(/'[^']+'/g);
  if (!quoted || quoted.length === 0) {
    console.error('Error: Could not find version in build.gradle');
    process.exit(1);
  }
  version = quoted[quoted.length - 1].slice(1, -1);
  console.log(`Found version in build.gradle: ${version}`);
}

// Create the version file for the webview
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
