// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.0.1',
    date: '2026-09-15',
    content: {
      en: `OpenCode Buddy — an opencode-only build of the plugin.

- Renamed to OpenCode Buddy: plugin id com.senjuobito.opencode-buddy, Java package com.opencodebuddy, tool window id OpenCode.
- Removed every non-opencode engine (Claude Agent SDK / Codex / Grok / Kimi / Pi / OMP / DSH / cc-switch provider management).
- The opencode pipeline now runs a persistent ai-bridge daemon + opencode serve (4096) + @opencode-ai/sdk v2 + SSE event stream instead of spawning the CLI per message.
- Session history now uses a local index + the daemon session.messages API; added /revert, /fork, compact, MCP status and question approval.
- @opencode-ai/sdk ships with the plugin, so the SDK no longer has to be installed on demand.
- Settings directory ~/.codemoss → ~/.opencodebuddy.`,
      zh: `OpenCode Buddy — opencode 专属改造版本。

- 插件更名 OpenCode Buddy：插件 ID com.senjuobito.opencode-buddy，Java 包名 com.opencodebuddy，工具窗口 ID OpenCode。
- 移除全部多引擎支持（Claude Agent SDK / Codex / Grok / Kimi / Pi / OMP / DSH / cc-switch 供应商管理）。
- opencode 链路升级为常驻 ai-bridge daemon + opencode serve (4096) + @opencode-ai/sdk v2 + SSE 事件流，替代每消息 spawn CLI。
- 会话历史改为本地索引 + daemon session.messages API；新增 /revert、/fork、compact、MCP 状态、question 审批。
- @opencode-ai/sdk 随插件打包，不再需要按需安装 SDK。
- 设置目录 ~/.codemoss → ~/.opencodebuddy。`,
    },
  },
];
